CREATE TABLE public.bits_po_entry_header (
    order_id integer NOT NULL,
    work_order character varying(255),
    plant_location character varying(255),
    department character varying(255),
    work_location character varying(255),
    work_order_date date,
    completion_date date,
    ld_applicable boolean,
    tenant_id integer,
    creation_date timestamp without time zone,
    created_by bigint,
    last_update_date timestamp without time zone,
    last_updated_by bigint,
    attribute1_v character varying(255),
    attribute2_v character varying(255),
    attribute3_v character varying(255),
    attribute4_v character varying(255),
    attribute5_v character varying(255),
    attribute1_n numeric,
    attribute2_n numeric,
    attribute3_n numeric,
    attribute4_n numeric,
    attribute5_n numeric,
    attribute1_d date,
    attribute2_d date,
    attribute3_d date,
    attribute4_d date,
    attribute5_d date,
    scrap_allowance_visible_percent character varying(255),
    scrap_allowance_invisible_percent character varying(255),
    material_issue_type character varying(255),
    customer_id bigint
);
