CREATE TABLE public.bits_po_entry_lines (
    line_id integer NOT NULL,
    line_number numeric,
    ser_no character varying(255),
    service_code character varying(255),
    service_desc character varying(255),
    qty numeric,
    uom character varying(255),
    unit_price numeric,
    total_price numeric,
    tenant_id integer,
    creation_date timestamp without time zone,
    created_by bigint,
    last_update_date timestamp without time zone,
    last_updated_by bigint,
    attribute1_v character varying(255),
    attribute2_v character varying(255),
    attribute3_v character varying(255),
    attribute4_v character varying(255),
    attribute5_v character varying(255),
    attribute1_n numeric,
    attribute2_n numeric,
    attribute3_n numeric,
    attribute4_n numeric,
    attribute5_n numeric,
    attribute1_d date,
    attribute2_d date,
    attribute3_d date,
    attribute4_d date,
    attribute5_d date,
    order_id integer
);
