CREATE TABLE public.core_lookup_values (
    lookup_type character varying(255) NOT NULL,
    language character varying(255) NOT NULL,
    lookup_code character varying(255) NOT NULL,
    meaning character varying(255) NOT NULL,
    description character varying(255),
    enabled_flag character varying(255) NOT NULL,
    start_date_active timestamp(6) without time zone,
    end_date_active timestamp(6) without time zone,
    created_by bigint NOT NULL,
    creation_date timestamp(6) without time zone NOT NULL,
    last_updated_by bigint NOT NULL,
    last_update_date timestamp(6) without time zone NOT NULL,
    source_lang character varying(255),
    security_group_id bigint DEFAULT 0 NOT NULL,
    view_application_id bigint NOT NULL,
    territory_code character varying(255),
    attribute_category character varying(255),
    attribute1 character varying(255),
    attribute2 character varying(255),
    attribute3 character varying(255),
    attribute4 character varying(255),
    attribute5 character varying(255),
    attribute6 character varying(255),
    attribute7 character varying(255),
    attribute8 character varying(255),
    attribute9 character varying(255),
    attribute10 character varying(255),
    attribute11 character varying(255),
    attribute12 character varying(255),
    attribute13 character varying(255),
    attribute14 character varying(255),
    attribute15 character varying(255),
    tag character varying(255),
    leaf_node character varying(255),
    tenant_id bigint,
    org_id bigint,
    lookup_type_desc character varying(255),
    editable_flag character varying(255) DEFAULT 'Y'::character varying NOT NULL,
    lookup_type_purpose character varying(255),
    id bigint NOT NULL
);
