CREATE TABLE public.cust_accounts (
    cust_account_id bigint NOT NULL,
    account_number character varying(30) NOT NULL,
    account_name character varying(240),
    last_update_date date NOT NULL,
    last_updated_by bigint NOT NULL,
    creation_date date NOT NULL,
    created_by bigint NOT NULL,
    attribute_category character varying(30),
    attribute1 character varying(150),
    attribute2 character varying(150),
    attribute3 character varying(150),
    attribute4 character varying(150),
    attribute5 character varying(150),
    attribute6 character varying(150),
    attribute7 character varying(150),
    attribute8 character varying(150),
    attribute9 character varying(150),
    attribute10 character varying(150),
    attribute11 character varying(150),
    attribute12 character varying(150),
    attribute13 character varying(150),
    attribute14 character varying(150),
    attribute15 character varying(150),
    attribute16 character varying(150),
    attribute17 character varying(150),
    attribute18 character varying(150),
    attribute19 character varying(150),
    attribute20 character varying(150),
    customer_type character varying(30),
    primary_salesrep_id bigint,
    order_id bigint,
    payment_term_id character varying(30),
    application_id integer,
    status character(1),
    orig_system_reference character varying(240),
    tenant_id integer,
    source character varying(50),
    orig_system_reference_value character varying(250),
    partner_id bigint,
    primary_flag character(1),
    billing_appl_id character varying(240),
    attribute21 character varying(150),
    attribute22 character varying(150),
    attribute23 character varying(150),
    attribute24 character varying(150),
    attribute25 character varying(150),
    attribute26 character varying(150),
    attribute27 character varying(150),
    attribute28 character varying(150),
    attribute29 character varying(150),
    attribute30 character varying(150),
    attribute_number1 numeric,
    attribute_number2 numeric,
    attribute_number3 numeric,
    attribute_number4 numeric,
    attribute_number5 numeric,
    attribute_number6 numeric,
    attribute_number7 numeric,
    attribute_number8 numeric,
    attribute_number9 numeric,
    attribute_number10 numeric,
    attribute_number11 numeric,
    attribute_number12 numeric,
    attribute_date1 date,
    attribute_date2 date,
    attribute_date3 date,
    attribute_date4 date,
    attribute_date5 date,
    attribute_date6 date,
    attribute_date7 date,
    attribute_date8 date,
    attribute_date9 date,
    attribute_date10 date,
    attribute_date11 date,
    attribute_date12 date,
    customer_class character varying(150),
    start_date_active date,
    end_date_active date,
    rule_name character varying(255)
);
