CREATE TABLE public.dbi_reports_all (
    report_id bigint NOT NULL,
    report_name character varying(100) NOT NULL,
    view_name character varying(100) NOT NULL,
    tenant_id bigint NOT NULL,
    group_name character varying(20),
    group_seq integer,
    report_display_seq integer,
    query_set_1 character varying(4000),
    query_set_2 character varying(4000),
    query_set_3 character varying(4000),
    query_set_4 character varying(4000),
    report_type character varying(100),
    query_set_5 character varying(4000),
    last_sync_date timestamp without time zone,
    incremental_rprt_flag character varying(20),
    description character varying(2000),
    report_category character varying(100),
    creation_date timestamp without time zone,
    created_by bigint,
    last_update_date timestamp without time zone,
    last_updated_by bigint,
    default_with_quotes character varying(1),
    read_only_flag character varying(1),
    query_set_6 character varying(4000),
    query_set_7 character varying(4000),
    query_set_8 character varying(4000),
    skip_threshold_limit character varying(1),
    enable_flag character varying(1),
    enable_incremental_flag character varying(1),
    incremental_source_column character varying(150),
    enable_incremental_timestamp character varying(1),
    incremental_start_date_column character varying(50),
    incremental_end_date_column character varying(50)
);
