CREATE TABLE public.erection_drawing_entry (
    line_id bigint NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    drawing_no character varying(255),
    mark_no character varying(255),
    marked_qty numeric(19,4),
    total_marked_wgt numeric(19,4),
    session_code character varying(255),
    session_name character varying(255),
    session_weight numeric(19,4),
    width numeric(19,4),
    length numeric(19,4),
    item_qty numeric(19,4),
    item_weight numeric(19,4),
    total_item_weight numeric(19,4),
    order_id bigint,
    ra_no character varying(255),
    tenant_id character varying(255),
    creation_date timestamp without time zone,
    created_by character varying(255),
    last_updating_date timestamp without time zone,
    last_updated_by character varying(255),
    attribute1_v character varying(255),
    attribute2_v character varying(255),
    attribute3_v character varying(255),
    attribute4_v character varying(255),
    attribute5_v character varying(255),
    attribute1_n numeric(19,4),
    attribute2_n numeric(19,4),
    attribute3_n numeric(19,4),
    attribute4_n numeric(19,4),
    attribute5_n numeric(19,4),
    attribute1_d date,
    attribute2_d date,
    attribute3_d date,
    attribute4_d date,
    attribute5_d date,
    po_line_reference_id numeric(19,4),
    status character varying(50),
    drawing_weight numeric(19,4),
    mark_weight numeric(19,4),
    drawing_received_date date,
    target_date date,
    cutting_stage character(1) DEFAULT 'N'::bpchar,
    fit_up_stage character(1) DEFAULT 'N'::bpchar,
    welding_stage character(1) DEFAULT 'N'::bpchar,
    finishing_stage character(1) DEFAULT 'N'::bpchar
);
