CREATE TABLE public.ledger_creation (
    id bigint NOT NULL,
    ledger_name character varying(255) NOT NULL,
    group_name character varying(255),
    debtor_creditor character varying(50),
    house_plot_no character varying(100),
    street character varying(255),
    village_post character varying(255),
    mandal_taluq character varying(255),
    district character varying(255),
    state character varying(255),
    pin_code character varying(10),
    contact_person_name character varying(255),
    mobile_no character varying(15),
    email character varying(255),
    website character varying(255),
    gstin character varying(15),
    pan character varying(10),
    bank_account_no character varying(50),
    ifsc_code character varying(11),
    branch_name character varying(255),
    service_type character varying(50),
    status character varying(20) DEFAULT 'ACTIVE'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
