CREATE TABLE public.m_order_header_all (
    order_id bigint NOT NULL,
    order_number character varying(150) NOT NULL,
    order_version bigint NOT NULL,
    status character varying(30) NOT NULL,
    ld_applicable character varying(1) DEFAULT 'N'::character varying,
    version bigint,
    source bigint,
    effective_start_date date,
    effective_end_date date,
    payment_term character varying(50),
    payment_method character varying(50),
    invoicing_rule character varying(50),
    currency character varying(3),
    price_list character varying(150),
    price numeric(38,2),
    batch_id bigint,
    order_type character varying(80),
    campaign_name character varying(250),
    reference_number character varying(150),
    deal_number character varying(150),
    file_name character varying(250),
    billing_channel character varying(50),
    order_category character varying(250),
    payment_amount numeric(38,2),
    booked_date date,
    activation_date date,
    termination_date date,
    legal_entity_id bigint,
    renewal_term bigint,
    renewal_date date,
    customer_source character varying(50),
    bill_to_customer_id bigint,
    bill_to_site_id bigint,
    bill_to_contact_id bigint,
    salesrep character varying(150),
    sell_to_customer_id bigint,
    sell_to_site_id bigint,
    sell_to_contact_id bigint,
    customer_contact_id bigint,
    customer_contact_phone character varying(20),
    customer_contact_email character varying(250),
    customer_po_number character varying(150),
    employee_id bigint,
    billing_batch character varying(50),
    billing_cycle character varying(25),
    billing_frequency character varying(50),
    min_ord_bill_amt numeric(38,2),
    max_ord_bill_amt numeric(38,2),
    next_renewal_date date,
    renewal_price_change numeric(38,2),
    delivery_channel character varying(50),
    total_order_budget numeric(38,2),
    notes character varying(250),
    creation_date timestamp without time zone,
    created_by bigint,
    last_update_date timestamp without time zone,
    last_updated_by bigint,
    source_id character varying(50),
    org_id bigint,
    tenant_id bigint,
    attribute_context character varying(150),
    attribute1_d date,
    attribute2_d date,
    attribute3_d date,
    attribute4_d date,
    attribute5_d date,
    attribute1_n numeric(38,2),
    attribute2_n numeric(38,2),
    attribute3_n numeric(38,2),
    attribute4_n numeric(38,2),
    attribute5_n numeric(38,2),
    attribute1_v character varying(250),
    attribute2_v character varying(250),
    attribute3_v character varying(250),
    attribute4_v character varying(250),
    attribute5_v character varying(250),
    attribute6_v character varying(250),
    attribute7_v character varying(250),
    attribute8_v character varying(250),
    attribute9_v character varying(250),
    attribute10_v character varying(250),
    attribute11_v character varying(250),
    attribute12_v character varying(250),
    attribute13_v character varying(250),
    attribute14_v character varying(250),
    attribute15_v character varying(250),
    check_number character varying(50),
    credit_card_type character varying(80),
    credit_card_number character varying(80),
    credit_card_holder_name character varying(80),
    credit_card_expiration_date date,
    credit_card_approval_code character varying(80),
    overage_frequency character varying(250),
    agency_discount numeric(38,2),
    salresrep_id bigint,
    salesrep_id bigint,
    price_list_id bigint,
    invoice_adj numeric(38,2),
    interface_adj numeric(38,2),
    billing_review_ind character varying(1) DEFAULT 'N'::character varying,
    spl_instr character varying(500),
    renewal_ind character varying(1),
    territory_code character varying(150),
    ext_reference_number character varying(150),
    cr character varying(20),
    evergreen_flag character varying(1),
    evergreen_end_date date,
    amendment_flag character varying(1),
    renew_flag character varying(1),
    original_order_number character varying(150)
);
