CREATE TABLE public.order_fabrication_import (
    iface_id bigint NOT NULL,
    iface_status character varying(250),
    error_message character varying(500),
    building_name character varying(250),
    drawing_no character varying(250),
    drawing_description character varying(250),
    order_number character varying(250),
    order_id bigint,
    orig_line_number bigint,
    orig_line_id bigint,
    line_number numeric(10,2),
    line_id bigint,
    erection_mkd character varying(250),
    item_no character varying(250),
    section character varying(250),
    length numeric,
    length_uom character varying(250),
    quantity numeric,
    unit_price numeric,
    unit_price_uom character varying(250),
    total_quantity numeric,
    total_quantity_uom character varying(250),
    original_quantity numeric,
    repeated_qty numeric,
    remark character varying(250),
    tenant_id bigint,
    creation_date date,
    created_by bigint,
    last_update_date date,
    last_updated_by bigint,
    org_id bigint,
    batch_name character varying(250)
);
