CREATE TABLE public.vendor_profile (
    id bigint NOT NULL,
    company_name character varying(255) NOT NULL,
    house_plot_no character varying(100),
    floor character varying(50),
    building_name character varying(255),
    street character varying(255),
    area character varying(255),
    village_post character varying(255),
    mandal_tq character varying(255),
    district character varying(255),
    state character varying(255),
    pin_code character varying(10),
    contact_person character varying(255),
    contact_number character varying(20),
    email character varying(255),
    logo_data bytea,
    logo_filename character varying(255),
    logo_content_type character varying(100),
    letter_head_data bytea,
    letter_head_filename character varying(255),
    letter_head_content_type character varying(100),
    bank_account character varying(50),
    ifsc_code character varying(15),
    branch_name character varying(255),
    gst_no character varying(15),
    pan_no character varying(10),
    status character varying(20) DEFAULT 'ACTIVE'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_email_format CHECK (((email IS NULL) OR ((email)::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text))),
    CONSTRAINT chk_gst_format CHECK (((gst_no IS NULL) OR (length((gst_no)::text) = 15))),
    CONSTRAINT chk_pan_format CHECK (((pan_no IS NULL) OR (length((pan_no)::text) = 10)))
);
